# Site Settings
name: Awesome WomenTechmakers
title: WomenTechmakers Korea 2019
description:
  - 우먼테크메이커스 장학생들이 자율적으로 운영하는 웹 사이트입니다.
  - Jekflix is a template for Jekyll inspired by Netflix and made by Thiago Rossener.
tags:
  - blog
  - womentechmakers
  - 우먼 테크메이커스
  - 장학생
  - wtm
  - jekyll
email: youremail@xyz.com
disqus_username: disqus_username
show_hero: true
paginate: 12

# Social Media Settings
# Remove the item if you don't need it
github_username: womentechkorea
facebook_username:
twitter_username:
instagram_username:
linkedin_username:
medium_username:


# Theme Settings
# themeColor: "#ff0a16"
primaryDark: "#141414"
accentDark: "#ffffff"
lightGray: "#f2f2f2"
texts: "#333333"

themeColor: "#ff9999" # pink
# primaryDark: "#ffffff"

# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: false


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-149894749-2"
language: "kr"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]
